{ pkgs, ... }: {
  environment.systemPackages = with pkgs; [
    exercism
    watch
    fd
    ncdu
    wget
    yq
    hub
    mas
    wtfutil
    gimp
    _1password-cli
    chatgpt
    brave
    gnupg
    pinentry_mac
    yubikey-manager
    yubikey-personalization
    paperkey
    pinentry-curses
    alt-tab-macos
    nur.repos.ohheyrj.garmin-basecamp
    nur.repos.ohheyrj.handbrake
    nur.repos.ohheyrj.chatterino
    nur.repos.ohheyrj.kobo-desktop
    nur.repos.ohheyrj.openaudible
    nur.repos.ohheyrj.ps-remote-play
    nur.repos.ohheyrj.bartender5
    nur.repos.ohheyrj.cryptomator
    nur.repos.ohheyrj.signal-desktop
    nur.repos.ohheyrj.alfred5
    nur.repos.ohheyrj.hazel
    slack
    discord
    age
    fzf
    gnupg
    gpgme
    htop
    inetutils
    jq
    mcfly
    mcfly-fzf
    mkpasswd
    neofetch
    nixos-rebuild
    nmap
    oh-my-posh
    ripgrep
    shellcheck
    speedtest-cli
    stow
    tmux
    tree
    zoxide
    sops
    utm
    nixos-generators
    dialog
    _7zz
    nix-search-tv

  ];
}
